# Generated by Django 5.1.3 on 2024-11-13 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manito', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manitomessage',
            name='giver',
        ),
        migrations.RemoveField(
            model_name='manitomessage',
            name='receiver',
        ),
    ]
